# -*- coding: utf-8 -*-
"""Source Code_UAS ADTT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6CtYSjyfEkFSVo7Dwt6G84z7VKqcjgJ
"""

# Install dependencies
!pip install ultralytics roboflow -q

# Verifikasi
import ultralytics
ultralytics.checks()

from roboflow import Roboflow

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="8u69KrRl36aMQwlwKEO9")
project = rf.workspace("fyp-ormnr").project("supermarket-empty-shelf-detector")
version = project.version(4)
dataset = version.download("yolov8")

import os

dataset_path = dataset.location
print("Dataset path:", dataset_path)

# Cek struktur folder
for split in ['train', 'valid', 'test']:
    img_path = os.path.join(dataset_path, split, 'images')
    lbl_path = os.path.join(dataset_path, split, 'labels')
    if os.path.exists(img_path):
        n_img = len(os.listdir(img_path))
        n_lbl = len(os.listdir(lbl_path)) if os.path.exists(lbl_path) else 0
        print(f"{split}: {n_img} images, {n_lbl} labels")

import yaml

yaml_path = os.path.join(dataset_path, 'data.yaml')
with open(yaml_path, 'r') as f:
    data_config = yaml.safe_load(f)

print(yaml.dump(data_config, default_flow_style=False))
# Pastikan: nc = 1, names = ['100- O-O-S']

import yaml, os

yaml_path = '/content/Supermarket-Empty-Shelf-Detector--4/data.yaml'

# Baca yaml
with open(yaml_path, 'r') as f:
    data = yaml.safe_load(f)

# Fix path ke absolute
base = '/content/Supermarket-Empty-Shelf-Detector--4'
data['train'] = os.path.join(base, 'train', 'images')
data['val']   = os.path.join(base, 'valid', 'images')
data['test']  = os.path.join(base, 'test',  'images')

# Simpan kembali
with open(yaml_path, 'w') as f:
    yaml.dump(data, f)

print("Path updated:")
print(f"  train: {data['train']}")
print(f"  val:   {data['val']}")
print(f"  test:  {data['test']}")

# Verifikasi folder benar-benar ada
for split, path in [('train', data['train']), ('val', data['val']), ('test', data['test'])]:
    exists = os.path.exists(path)
    n = len(os.listdir(path)) if exists else 0
    print(f"  {split}: exists={exists}, files={n}")

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.train(
    data='/content/Supermarket-Empty-Shelf-Detector--4/data.yaml',
    epochs=100,
    imgsz=640,
    batch=16,
    name='oos_yolov8n',
    project='/content/runs/detect',
    patience=20,
    save=True,
    plots=True,
    verbose=True
)

print("\n=== TRAINING SELESAI ===")
print(f"Best weights: /content/runs/detect/oos_yolov8n/weights/best.pt")

""" Evaluasi pada Test Set"""

from ultralytics import YOLO

model_best = YOLO('/content/runs/detect/oos_yolov8n/weights/best.pt')

metrics = model_best.val(
    data='/content/Supermarket-Empty-Shelf-Detector--4/data.yaml',
    split='test',
    plots=True,
    save_json=False,
    name='oos_test_eval',
    project='/content/runs/detect'
)

print("\n=== HASIL EVALUASI TEST SET ===")
print(f"Precision : {metrics.box.p[0]:.4f}")
print(f"Recall    : {metrics.box.r[0]:.4f}")
print(f"mAP@50    : {metrics.box.map50:.4f}")
print(f"mAP@50-95 : {metrics.box.map:.4f}")

# F1-score manual
p = metrics.box.p[0]
r = metrics.box.r[0]
f1 = 2 * p * r / (p + r)
print(f"F1-score  : {f1:.4f}")

import glob, random
from IPython.display import Image, display

# Prediksi semua gambar test
results_pred = model_best.predict(
    source='/content/Supermarket-Empty-Shelf-Detector--4/test/images',
    conf=0.25,
    save=True,
    project='/content/runs/detect',
    name='oos_test_predict'
)

# Tampilkan 6 sampel hasil prediksi
pred_imgs = sorted(glob.glob('/content/runs/detect/oos_test_predict/*.jpg'))
print(f"Total gambar prediksi: {len(pred_imgs)}")

for img in pred_imgs[:6]:
    print(img)
    display(Image(img, width=600))

import os
from IPython.display import Image, display

viz_dir = '/content/runs/detect/oos_yolov8n'
poster_files = [
    'results.png',
    'confusion_matrix.png',
    'confusion_matrix_normalized.png',
    'PR_curve.png',
    'F1_curve.png',
    'val_batch0_labels.jpg',
    'val_batch0_pred.jpg'
]

for fname in poster_files:
    fpath = os.path.join(viz_dir, fname)
    if os.path.exists(fpath):
        print(f"✅ {fname}")
        display(Image(fpath, width=600))
    else:
        print(f"❌ {fname} — tidak ditemukan")

import shutil
from google.colab import files

# Zip semua hasil
shutil.make_archive('/content/uas_adtt_hasil', 'zip', '/content/runs/detect')
files.download('/content/uas_adtt_hasil.zip')
print("Download dimulai.")